<?php

$t_language_text_section_content_array = [
    'mollie_title'                   => 'Mollie',
    'mollie_description'             => 'Modulo di pagamento Mollie',
    'mollie_version'                 => 'Versione',
    'mollie_test_mode'               => 'Modalità di test',
    'mollie_live_token'              => 'Chiave API live',
    'mollie_test_token'              => 'Chiave API di test',
    'mollie_live_token_msg'          => 'Puoi trovare la tua chiave API live nel tuo <a href="https://www.mollie.com/dashboard/developers/api-keys" target="_blank">Profilo Mollie</a>.',
    'mollie_test_token_msg'          => 'Puoi trovare la tua chiave API di test nel tuo <a href="https://www.mollie.com/dashboard/developers/api-keys" target="_blank">Profilo Mollie</a>.',
    'mollie_verify'                  => 'Verifica token',
    'mollie_support'                 => 'Supporto',
    'mollie_support_link'            => 'https://help.mollie.com/hc/it',
    'mollie_status'                  => 'Stato',
    'mollie_connect_success'         => '<i class="fa fa-check"></i> Connessione stabilita con successo con la <b>chiave API {key_type}</b>. <br><br><i class="fa fa-cog"></i> Metodi abilitati: {enabled_methods}',
    'mollie_connect_failure'         => '<i class="fa fa-times"></i> Chiave API <b>{key_type}</b> non valida. {api_message}',
    'mollie_keys_missing'            => '<i class="fa fa-times"></i> Per favore fornisci almeno una chiave API',
    'mollie_configuration_failure'   => '<i class="fa fa-times"></i> Errore durante il salvataggio della configurazione Mollie: {api_message}',
    'mollie_active'                  => 'Attivo',
    'mollie_inactive'                => 'Inattivo',
    'mollie_configure'               => 'Configura',
    'mollie_payment_methods'         => 'Metodi di pagamento',
    'mollie_configuration'           => 'Configurazione Mollie',
    'mollie_enabled'                 => 'Abilitato',
    'mollie_disabled'                => 'Disabilitato',
    'mollie_connected'               => 'Connesso',
    'mollie_not_connected'           => 'Non connesso',
    'mollie_notifications'           => 'Notifiche',
    'mollie_date'                    => 'Data',
    'mollie_type'                    => 'Tipo',
    'mollie_order_number'            => 'Numero ordine',
    'mollie_message'                 => 'Messaggio',
    'mollie_details'                 => 'Dettagli',
    'mollie_info'                    => 'Info',
    'mollie_warning'                 => 'Avviso',
    'mollie_error'                   => 'Errore',
    'mollie_order_statuses'          => 'Stati ordine',
    'mollie_created'                 => 'Creato',
    'mollie_authorized'              => 'Autorizzato',
    'mollie_paid'                    => 'Pagato',
    'mollie_refunded'                => 'Rimborsato',
    'mollie_none'                    => 'Nessuno',
    'mollie_cancel'                  => 'Annulla',
    'mollie_save_changes'            => 'Salva modifiche',
    'mollie_save_mapping_success'    => 'Mappatura stato ordine aggiornata con successo',
    'mollie_save_mapping_error'      => 'Impossibile salvare gli stati ordine: {message}',
    'mollie_dashboard_title'         => 'Informazioni pagamento Mollie',
    'mollie_payment_method'          => 'Metodo di pagamento',
    'mollie_checkout_type'           => 'Tipo di checkout',
    'mollie_payment_status'          => 'Stato pagamento',
    'mollie_order_status'            => 'Stato ordine',
    'mollie_paid_amount'             => 'Importo',
    'mollie_refunded_amount'         => 'Importo rimborsato',
    'mollie_payment_link'            => 'Link pagamento',
    'mollie_shipments'               => 'Spedizioni',
    'mollie_refunds'                 => 'Rimborsi',
    'mollie_open_in_mollie'          => 'Apri in Mollie',
    'mollie_payment_link_message'    => 'Il pagamento è ancora in sospeso? Copia questo link di pagamento e invialo al cliente. Lo reindirizzerà alla pagina di checkout per ripetere il pagamento.',
    'mollie_items'                   => 'Articoli',
    'mollie_amount'                  => 'Importo',
    'mollie_model'                   => 'Modello',
    'mollie_products'                => 'Prodotti',
    'mollie_ordered_qty'             => 'Quantità ordinata',
    'mollie_shipped_qty'             => 'Quantità spedita',
    'mollie_shipped_at'              => 'Spedito il',
    'mollie_qty_to_ship'             => 'Quantità da spedire',
    'mollie_carrier'                 => 'Corriere',
    'mollie_tracking_code'           => 'Codice tracciamento',
    'mollie_tracking_url'            => 'URL tracciamento',
    'mollie_submit_shipment'         => 'Invia spedizione',
    'mollie_copy_to_clipboard'       => 'Copia negli appunti',
    'mollie_refund'                  => 'Rimborso',
    'mollie_refunded_qty'            => 'Quantità rimborsata',
    'mollie_qty_to_refund'           => 'Quantità da rimborsare',
    'mollie_payment_refund'          => 'Rimborso pagamento',
    'mollie_refund_amount'           => 'Importo rimborso',
    'mollie_refund_reason'           => 'Motivo del rimborso',
    'mollie_total'                   => 'Totale',
    'mollie_price'                   => 'Prezzo',
    'mollie_refund_message'          => 'Questo pagamento è stato effettuato come parte di un ordine; si consiglia di rimborsare le singole righe dell\'ordine.',
    'mollie_total_refunded'          => 'Importo già rimborsato',
    'mollie_available_to_refund'     => 'Importo rimborsabile residuo',
    'mollie_refund_success'          => 'Pagamento rimborsato con successo',
    'mollie_refund_error'            => 'Il pagamento non può essere rimborsato. Risposta API Mollie: ',
    'mollie_not_refundable'          => 'L\'importo totale è già stato rimborsato',
    'mollie_not_shippable'           => 'Tutti gli articoli sono già stati spediti',
    'mollie_shipment_create_success' => 'Spedizione creata con successo su Mollie',
    'mollie_shipment_create_error'   => 'Impossibile creare la spedizione per l\'ordine Mollie correlato. Risposta API Mollie {api_message}',
    'mollie_change_logo'             => 'Cambia logo',
    'mollie_change_logo_error'       => 'Caricamento logo fallito',
    'mollie_orders_api'              => 'API Ordini',
    'mollie_payments_api'            => 'API Pagamenti',
    'mollie_unknown_error'           => 'Errore sconosciuto verificatosi nell\'API Mollie',
    'mollie_checkout_desc'           => 'Dopo la revisione dell\'ordine verrai reindirizzato al sito del gateway di pagamento per completare l\'acquisto.',
    'mollie_single_click_payment_approval_text' => 'Salva la carta di credito per acquisti futuri',
    'mollie_single_click_payment_desc' => "Hai già salvato la tua carta. Verrai reindirizzato a Mollie.",
    'mollie_surcharge_type_no_fee'   => 'Nessuna commissione',
    'mollie_surcharge_type_fixed_fee' => 'Commissione fissa',
    'mollie_surcharge_type_percentage' => 'Percentuale',
    'mollie_surcharge_type_fixed_fee_and_percentage' => 'Commissione fissa e percentuale',

    'mollie_issuer_list_dropdown'    => 'Menu a discesa',
    'mollie_issuer_list_images'      => 'Elenco con immagini',
    'mollie_issuer_not_selected'     => 'Emittente non selezionato',

    'mollie_select_bank'             => 'Seleziona banca',
    'mollie_card_holder'             => 'Nome sulla carta',
    'mollie_card_number'             => 'Numero carta',
    'mollie_expiry_date'             => 'Data di scadenza',
    'mollie_verification_code'       => 'CVC/CVV',
    'mollie_use_saved_credit_card_text' => 'Usa le informazioni della carta di credito salvata',

    'mollie_transaction_desc_label' => 'Descrizione da usare per la transazione di pagamento. Variabili disponibili: {orderNumber}, {storeName}, {customerFirstname}, {customerLastname}, {customerCompany}, {cartNumber}.',

    'mollie_canceled_comment' => 'Il cliente ha annullato il pagamento.',
    'mollie_expired_comment'  => 'Il pagamento è scaduto su Mollie.',
    'mollie_failed_comment'   => 'Il pagamento è fallito e non può essere completato con il metodo selezionato.',

    'mollie.payment.integration.event.notification.order_cancel_error.title'       => 'Sincronizzazione modifica negozio fallita',
    'mollie.payment.integration.event.notification.order_cancel_error.description' => 'Impossibile annullare ordine Mollie. Risposta API Mollie {api_message}',

    'mollie.payment.integration.event.notification.order_cancel.title'       => 'Evento di annullamento ordine rilevato',
    'mollie.payment.integration.event.notification.order_cancel.description' => 'L\'annullamento dell\'ordine non è supportato, quindi questa modifica non viene sincronizzata con Mollie',

    'mollie.payment.integration.event.notification.billing_address_change_error.title'       => 'Sincronizzazione modifica negozio fallita',
    'mollie.payment.integration.event.notification.billing_address_change_error.description' => 'Impossibile aggiornare l\'indirizzo di fatturazione nell\'ordine Mollie. Risposta API Mollie {api_message}',

    'mollie_version_outdated_message' => 'È disponibile una nuova versione del modulo {versionNumber}. Scarica l\'ultima versione <a href="{downloadUrl}" target="_blank">qui</a>',
    'mollie_system_offline_message'   => 'Il tuo sito web è in modalità offline. Poiché Mollie invia messaggi al tuo sito quando lo stato del pagamento cambia, Mollie non potrà accedere al sito in modalità offline.',

    'mollie_status_label'          => 'Stato Mollie',
    'mollie_gambio_status_label'   => 'Stato Gambio',
    'mollie_method_label'          => 'Metodo',
];
