<?php

$t_language_text_section_content_array = [
    'mollie_title'                   => 'Mollie',
    'mollie_description'             => 'Module de paiement Mollie',
    'mollie_version'                 => 'Version',
    'mollie_test_mode'               => 'Mode test',
    'mollie_live_token'              => 'Clé API live',
    'mollie_test_token'              => 'Clé API test',
    'mollie_live_token_msg'          => 'Vous trouverez votre clé API live dans votre <a href="https://www.mollie.com/dashboard/developers/api-keys" target="_blank">profile Mollie</a>.',
    'mollie_test_token_msg'          => 'Vous trouverez votre clé API test dans votre <a href="https://www.mollie.com/dashboard/developers/api-keys" target="_blank">profile Mollie</a>.',
    'mollie_verify'                  => 'Vérifier les jetons',
    'mollie_support'                 => 'Assistance',
    'mollie_support_link'            => 'https://help.mollie.com/hc/en-us',
    'mollie_status'                  => 'Statut',
    'mollie_connect_success'         => "<i class='fa fa-check'></i> Une connexion a été correctement établie avec l' <b>{key_type} API</b>.<br><br><i class='fa fa-cog'></i> Méthodes activées: {enabled_methods}",
    'mollie_connect_failure'         => "<i class='fa fa-times'></i> Une erreur d'authentification est survenue. Profil des jetons d'authentification non valide.",
    'mollie_keys_missing'            => '<i class="fa fa-times"></i> Veuillez fournir au moins une clé API',
    'mollie_configuration_failure'   => '<i class="fa fa-times"></i> Une erreur lors de la sauvegarde de la configuration de Mollie: {api_message}',
    'mollie_active'                  => 'Actif',
    'mollie_inactive'                => 'Inactif',
    'mollie_configure'               => 'Configurer',
    'mollie_payment_methods'         => 'Moyens de paiement',
    'mollie_configuration'           => 'Configuration de Mollie',
    'mollie_enabled'                 => 'Activé',
    'mollie_disabled'                => 'Désactivé',
    'mollie_connected'               => 'Connecté',
    'mollie_not_connected'           => 'Non connecté',
    'mollie_notifications'           => 'Notifications',
    'mollie_date'                    => 'Date',
    'mollie_type'                    => 'Type',
    'mollie_order_number'            => 'Numéro de commande',
    'mollie_message'                 => 'Message',
    'mollie_details'                 => 'Détails',
    'mollie_info'                    => 'Information',
    'mollie_warning'                 => 'Attention',
    'mollie_error'                   => 'Erreur',
    'mollie_order_statuses'          => 'Statuts de commande',
    'mollie_created'                 => 'Créé',
    'mollie_authorized'              => 'Autorisé',
    'mollie_paid'                    => 'Payé',
    'mollie_refunded'                => 'Remboursé',
    'mollie_none'                    => 'Aucun',
    'mollie_cancel'                  => 'Annuler',
    'mollie_save_changes'            => 'Sauvegarder les changements',
    'mollie_dashboard_title'         => 'Information de paiement Mollie',
    'mollie_payment_method'          => 'Moyen de paiement',
    'mollie_checkout_type'           => 'Type de checkout',
    'mollie_payment_status'          => 'Statut de paiement',
    'mollie_order_status'            => 'Statuts de commande',
    'mollie_paid_amount'             => 'Montant payé',
    'mollie_refunded_amount'         => 'Montant remboursé',
    'mollie_payment_link'            => 'Lien de paiement',
    'mollie_shipments'               => 'Envois',
    'mollie_refunds'                 => 'Remboursements',
    'mollie_open_in_mollie'          => 'Open in Mollie',
    'mollie_payment_link_message'    => 'Votre paiement est toujours en attente ? Copiez ce lien de paiement et envoyez-le à votre client. Cela le redirigera vers la page de checkout où il pourra à nouveau procéder au paiement',
    'mollie_items'                   => 'Articles',
    'mollie_amount'                  => 'Montant',
    'mollie_model'                   => 'Modèle',
    'mollie_products'                => 'Produits',
    'mollie_ordered_qty'             => 'Qté commandée',
    'mollie_shipped_qty'             => 'Qté envoyée',
    'mollie_shipped_at'              => 'Shipped at',
    'mollie_qty_to_ship'             => 'Qté à envoyer',
    'mollie_carrier'                 => 'Transporteur',
    'mollie_tracking_code'           => 'Code de suivi',
    'mollie_tracking_url'            => 'URL de suivi',
    'mollie_submit_shipment'         => "Soumettre l'envoi",
    'mollie_copy_to_clipboard'       => 'Copier dans le presse-papier',
    'mollie_refund'                  => 'Rembourser',
    'mollie_refunded_qty'            => 'Qté remboursée',
    'mollie_qty_to_refund'           => 'Qté à rembourser',
    'mollie_payment_refund'          => 'Remboursement du paiement',
    'mollie_refund_amount'           => 'Montant du remboursement',
    'mollie_refund_reason'           => 'Raison du remboursement',
    'mollie_total'                   => 'Total',
    'mollie_price'                   => 'Prix',
    'mollie_refund_message'          => "Ce payement a été réalisé comme partie d'une commande et il est recommandé de rembourser les lignes de commande individuelles.",
    'mollie_total_refunded'          => 'Montant déjà remboursé',
    'mollie_available_to_refund'     => 'Montant remboursable restant',
    'mollie_refund_success'          => 'Le paiement a été correctement remboursé',
    'mollie_refund_error'            => "Le payement ne peut pas être remboursé. Réponse de l'api Mollie: ",
    'mollie_not_refundable'          => 'Le montant total a déjà été remboursé',
    'mollie_not_shippable'           => 'All items have been already shipped',
    'mollie_shipment_create_success' => 'Envoi correctement créé sur Mollie',
    'mollie_shipment_create_error'   => "Échec de la création d'un envoi pour la commande Mollie associée. Réponse de l'api Mollie {api_message}",
    'mollie_change_logo'             => 'Change logo',
    'mollie_change_logo_error'       => 'Failed to upload logo',
    'mollie_orders_api'              => 'API de commande',
    'mollie_payments_api'            => 'API de paiement',
    'mollie_unknown_error'           => 'Unknown error occurred on Mollie API',
    'mollie_checkout_desc'           => "Vous allez être redirigé vers le site web de la passerelle de paiement pour effectuer votre achat après l'étape de révision de la commande.",

    'mollie_issuer_list_dropdown'    => 'Liste déroulante',
    'mollie_issuer_list_images'      => 'Liste avec images',
    'mollie_issuer_not_selected'     => 'Émetteur non sélectionné',


    'mollie_select_bank'             => 'Choisir une banque',
    'mollie_card_holder'             => 'Nom du titulaire de la carte',
    'mollie_card_number'             => 'Numero de carte de credit',
    'mollie_expiry_date'             => 'MM/AA',
    'mollie_verification_code'       => 'CVV',

    'mollie_transaction_desc_label' => 'La description à utiliser pour la transaction de paiement. Ces variables sont disponibles: {orderNumber}, {storeName}, {customerFirstname}, {customerLastname}, {customerCompany} et {cartNumber}.',

    'mollie_canceled_comment' => 'Le client a annulé le paiement.',
    'mollie_expired_comment'  => 'Le paiement a expiré sur Mollie.',
    'mollie_failed_comment'   => 'La paiement a échoué et ne peut pas être effectué avec le moyen de paiement sélectionné.',

    'mollie.payment.integration.event.notification.order_cancel_error.title'       => 'La synchronisation du changement de magasin a échoué',
    'mollie.payment.integration.event.notification.order_cancel_error.description' => "Échec de l'annulation de la commande Mollie. Réponse de l'api Mollie {api_message}",

    'mollie.payment.integration.event.notification.order_cancel.title'       => "Événement d'annulation de commande détecté",
    'mollie.payment.integration.event.notification.order_cancel.description' => "L'annulation de commande n'est pas prise en charge, donc cette modification n'est pas synchronisée avec le Mollie",

    'mollie.payment.integration.event.notification.billing_address_change_error.title'       => 'La synchronisation du changement de magasin a échoué',
    'mollie.payment.integration.event.notification.billing_address_change_error.description' => "Échec de la mise à jour de l'adresse de facturation de la commande Mollie. Réponse de l'api Mollie {api_message}",

    'mollie.payment.integration.event.notification.shipping_address_change_error.title'       => 'La synchronisation du changement de magasin a échoué',
    'mollie.payment.integration.event.notification.shipping_address_change_error.description' => "Échec de la mise à jour de l'adresse de livraison de la commande Mollie. Réponse de l'api Mollie {api_message}",

    'mollie.payment.integration.event.notification.order_line_changed_error.title'       => 'La synchronisation de la ligne de commande a échoué',
    'mollie.payment.integration.event.notification.order_line_changed_error.description' => "Échec de la mise à jour de la ligne de commande pour la commande Mollie associée. Réponse de l'api Mollie {api_message}",

    'mollie.payment.integration.event.notification.order_ship_error.title'       => 'La synchronisation du changement de magasin a échoué',
    'mollie.payment.integration.event.notification.order_ship_error.description' => "Échec de la création d'un envoi pour la commande Mollie associée. Réponse de l'api Mollie {api_message}",

    'mollie.payment.integration.event.notification.order_total_changed.title'       => 'Événement détecté de changement total de commande',
    'mollie.payment.integration.event.notification.order_total_changed.description' => "La changement total de commande n'est pas pris en charge, ce changement n'est donc pas synchronisé avec Mollie",

    'mollie.payment.webhook.notification.order_line_refund_info.title'       => 'La ligne de commande Mollie a changé',
    'mollie.payment.webhook.notification.order_line_refund_info.description' => 'La ligne de commande est remboursée sur le portail Mollie.',

    'mollie.payment.webhook.notification.invalid_shop_order.title'       => 'Changement Mollie pour une commande inconnue',
    'mollie.payment.webhook.notification.invalid_shop_order.description' => "Le changement depuis Mollie est détecté mais la commande correspondante n'a pas été trouvée dans le système.",

    'mollie.payment.webhook.notification.invalid_credentials.title'       => "Le changement de Mollie n'est pas synchronisé",
    'mollie.payment.webhook.notification.invalid_credentials.description' => "Une erreur d'authentification est survenue. Organisation des jetons d'authentification non valide.",

    'mollie.payment.webhook.notification.invalid_api_order.title'       => 'Changement Mollie pour une commande inconnue',
    'mollie.payment.webhook.notification.invalid_api_order.description' => "Le changement depuis Mollie est détecté mais le paiement correspondant n'a pas été trouvé dans l'api Mollie. Réponse de l'api Mollie {api_message}",

    'mollie.payment.webhook.notification.network_communication_problem.title'       => "Le changement de Mollie n'est pas synchronisé",
    'mollie.payment.webhook.notification.network_communication_problem.description' => "Le changement depuis Mollie est déctecté mais la connexion au réseau avec l'API Mollie n'a pas été établie. Détails techniques: {technical_message}",

    'mollie.payment.webhook.notification.order_pay_error.title'       => "Le changement de Mollie n'est pas synchronisé",
    'mollie.payment.webhook.notification.order_pay_error.description' => 'La commande est payée sur le portail Mollie.',

    'mollie.payment.webhook.notification.order_expire_error.title'       => "Le changement de Mollie n'est pas synchronisé",
    'mollie.payment.webhook.notification.order_expire_error.description' => 'La commande est expirée sur le portail Mollie.',

    'mollie.payment.webhook.notification.order_cancel_error.title'       => "Le changement de Mollie n'est pas synchronisé",
    'mollie.payment.webhook.notification.order_cancel_error.description' => 'La commande est annulée sur le portail Mollie.',

    'mollie.payment.webhook.notification.order_refund_error.title'       => "Le changement de Mollie n'est pas synchronisé",
    'mollie.payment.webhook.notification.order_refund_error.description' => 'La commande est remboursée sur le portail Mollie.',

    'mollie.payment.webhook.notification.order_line_cancel_info.title'       => 'La ligne de commande Mollie a changé',
    'mollie.payment.webhook.notification.order_line_cancel_info.description' => 'La ligne de commande est annulée sur le portail Mollie.',

    'mollie_version_outdated_message' => "Une nouvelle version du module {versionNumber} est disponible. Veuillez télécharger la dernière version <a href='{downloadUrl}' target='_blank'>here</a>",
    'mollie_system_offline_message'   => "Votre site Web fonctionne en mode hors ligne. Étant donné que Mollie envoie un message à votre site Web lorsque l'état du paiement change, Mollie ne pourra pas accéder à votre site Web en mode hors connexion",

    'mollie_status_label'          => 'Statut Mollie',
    'mollie_gambio_status_label'   => 'Statut Gambio',
    'mollie_method_label'          => 'Méthode',

];