<?php

$t_language_text_section_content_array = [
    'mollie_title'                   => 'Mollie',
    'mollie_description'             => 'Módulo de pago Mollie',
    'mollie_version'                 => 'Versión',
    'mollie_test_mode'               => 'Modo de prueba',
    'mollie_live_token'              => 'Clave API en vivo',
    'mollie_test_token'              => 'Clave API de prueba',
    'mollie_live_token_msg'          => 'Puedes encontrar tu clave API en vivo en tu <a href="https://www.mollie.com/dashboard/developers/api-keys" target="_blank">Perfil de Mollie</a>.',
    'mollie_test_token_msg'          => 'Puedes encontrar tu clave API de prueba en tu <a href="https://www.mollie.com/dashboard/developers/api-keys" target="_blank">Perfil de Mollie</a>.',
    'mollie_verify'                  => 'Verificar token',
    'mollie_support'                 => 'Soporte',
    'mollie_support_link'            => 'https://help.mollie.com/hc/en-us',
    'mollie_status'                  => 'Estado',
    'mollie_connect_success'         => '<i class="fa fa-check"></i> La conexión se estableció correctamente con la clave API <b>{key_type}</b>. <br><br><i class="fa fa-cog"></i> Métodos habilitados: {enabled_methods}',
    'mollie_connect_failure'         => '<i class="fa fa-times"></i> Clave API <b>{key_type}</b> inválida. {api_message}',
    'mollie_keys_missing'            => '<i class="fa fa-times"></i> Por favor, proporciona al menos una clave API',
    'mollie_configuration_failure'   => '<i class="fa fa-times"></i> Error al guardar la configuración de Mollie: {api_message}',
    'mollie_active'                  => 'Activo',
    'mollie_inactive'                => 'Inactivo',
    'mollie_configure'               => 'Configurar',
    'mollie_payment_methods'         => 'Métodos de pago',
    'mollie_configuration'           => 'Configuración de Mollie',
    'mollie_enabled'                 => 'Habilitado',
    'mollie_disabled'                => 'Deshabilitado',
    'mollie_connected'               => 'Conectado',
    'mollie_not_connected'           => 'No conectado',
    'mollie_notifications'           => 'Notificaciones',
    'mollie_date'                    => 'Fecha',
    'mollie_type'                    => 'Tipo',
    'mollie_order_number'            => 'Número de pedido',
    'mollie_message'                 => 'Mensaje',
    'mollie_details'                 => 'Detalles',
    'mollie_info'                    => 'Información',
    'mollie_warning'                 => 'Advertencia',
    'mollie_error'                   => 'Error',
    'mollie_order_statuses'          => 'Estados del pedido',
    'mollie_created'                 => 'Creado',
    'mollie_authorized'              => 'Autorizado',
    'mollie_paid'                    => 'Pagado',
    'mollie_refunded'                => 'Reembolsado',
    'mollie_none'                    => 'Ninguno',
    'mollie_cancel'                  => 'Cancelar',
    'mollie_save_changes'            => 'Guardar cambios',
    'mollie_save_mapping_success'    => 'Asignación de estados del pedido actualizada con éxito',
    'mollie_save_mapping_error'      => 'Error al guardar los estados del pedido: {message}',
    'mollie_dashboard_title'         => 'Información de pago Mollie',
    'mollie_payment_method'          => 'Método de pago',
    'mollie_checkout_type'           => 'Tipo de pago',
    'mollie_payment_status'          => 'Estado del pago',
    'mollie_order_status'            => 'Estado del pedido',
    'mollie_paid_amount'             => 'Cantidad',
    'mollie_refunded_amount'         => 'Cantidad reembolsada',
    'mollie_payment_link'            => 'Enlace de pago',
    'mollie_shipments'               => 'Envíos',
    'mollie_refunds'                 => 'Reembolsos',
    'mollie_open_in_mollie'          => 'Abrir en Mollie',
    'mollie_payment_link_message'    => '¿Tu pago sigue pendiente? Copia este enlace de pago y envíaselo a tu cliente. Les redirigirá a la página de pago, donde podrán iniciar el pago nuevamente.',
    'mollie_items'                   => 'Artículos',
    'mollie_amount'                  => 'Cantidad',
    'mollie_model'                   => 'Modelo',
    'mollie_products'                => 'Productos',
    'mollie_ordered_qty'             => 'Cantidad pedida',
    'mollie_shipped_qty'             => 'Cantidad enviada',
    'mollie_shipped_at'              => 'Enviado en',
    'mollie_qty_to_ship'             => 'Cantidad a enviar',
    'mollie_carrier'                 => 'Transportista',
    'mollie_tracking_code'           => 'Código de seguimiento',
    'mollie_tracking_url'            => 'URL de seguimiento',
    'mollie_submit_shipment'         => 'Enviar envío',
    'mollie_copy_to_clipboard'       => 'Copiar al portapapeles',
    'mollie_refund'                  => 'Reembolso',
    'mollie_refunded_qty'            => 'Cantidad reembolsada',
    'mollie_qty_to_refund'           => 'Cantidad a reembolsar',
    'mollie_payment_refund'          => 'Reembolso de pago',
    'mollie_refund_amount'           => 'Cantidad de reembolso',
    'mollie_refund_reason'           => 'Razón del reembolso',
    'mollie_total'                   => 'Total',
    'mollie_price'                   => 'Precio',
    'mollie_refund_message'          => 'Este pago se realizó como parte de un pedido y se recomienda reembolsar líneas individuales del pedido.',
    'mollie_total_refunded'          => 'Cantidad ya reembolsada',
    'mollie_available_to_refund'     => 'Cantidad restante para reembolsar',
    'mollie_refund_success'          => 'Pago reembolsado con éxito',
    'mollie_refund_error'            => 'El pago no se puede reembolsar. Respuesta de la API Mollie: ',
    'mollie_not_refundable'          => 'La cantidad total ya ha sido reembolsada',
    'mollie_not_shippable'           => 'Todos los artículos ya han sido enviados',
    'mollie_shipment_create_success' => 'Envío creado con éxito en Mollie',
    'mollie_shipment_create_error'   => 'Error al crear el envío para el pedido Mollie relacionado. Respuesta de la API Mollie {api_message}',
    'mollie_change_logo'             => 'Cambiar logo',
    'mollie_change_logo_error'       => 'Error al subir el logo',
    'mollie_orders_api'              => 'API de pedidos',
    'mollie_payments_api'            => 'API de pagos',
    'mollie_unknown_error'           => 'Error desconocido en la API Mollie',
    'mollie_checkout_desc'           => 'Serás redirigido al sitio web del proveedor de pago para completar tu compra después del paso de revisión del pedido.',
    'mollie_single_click_payment_approval_text' => 'Guardar tarjeta de crédito para futuras compras',
    'mollie_single_click_payment_desc' => 'Has guardado tu tarjeta previamente. Serás redirigido a Mollie.',
    'mollie_surcharge_type_no_fee'   => 'Sin cargo',
    'mollie_surcharge_type_fixed_fee' => 'Cargo fijo',
    'mollie_surcharge_type_percentage' => 'Porcentaje',
    'mollie_surcharge_type_fixed_fee_and_percentage' => 'Cargo fijo y porcentaje',

    'mollie_issuer_list_dropdown'    => 'Desplegable',
    'mollie_issuer_list_images'      => 'Lista con imágenes',
    'mollie_issuer_not_selected'     => 'Emisor no seleccionado',

    'mollie_select_bank'             => 'Seleccionar banco',
    'mollie_card_holder'             => 'Nombre en la tarjeta',
    'mollie_card_number'             => 'Número de tarjeta',
    'mollie_expiry_date'             => 'Fecha de expiración',
    'mollie_verification_code'       => 'CVC/CVV',
    'mollie_use_saved_credit_card_text' => 'Usar información de tarjeta guardada',

    'mollie_transaction_desc_label' => 'Descripción a usar para la transacción de pago. Variables disponibles: {orderNumber}, {storeName}, {customerFirstname}, {customerLastname}, {customerCompany} y {cartNumber}.',

    'mollie_canceled_comment' => 'El cliente ha cancelado el pago.',
    'mollie_expired_comment'  => 'El pago ha expirado en Mollie.',
    'mollie_failed_comment'   => 'El pago ha fallado y no puede completarse con el método seleccionado.',

    'mollie.payment.integration.event.notification.order_cancel_error.title'       => 'Error de sincronización de cambios en la tienda',
    'mollie.payment.integration.event.notification.order_cancel_error.description' => 'No se pudo cancelar el pedido Mollie. Respuesta de la API Mollie {api_message}',

    'mollie.payment.integration.event.notification.order_cancel.title'       => 'Evento de cancelación de pedido detectado',
    'mollie.payment.integration.event.notification.order_cancel.description' => 'La cancelación de pedidos no está soportada, por lo que este cambio no se sincroniza con Mollie',

    'mollie.payment.integration.event.notification.billing_address_change_error.title'       => 'Error de sincronización de cambios en la tienda',
    'mollie.payment.integration.event.notification.billing_address_change_error.description' => 'No se pudo actualizar la dirección de facturación en el pedido Mollie. Respuesta de la API Mollie {api_message}',

    'mollie.payment.integration.event.notification.shipping_address_change_error.title'       => 'Error de sincronización de cambios en la tienda',
    'mollie.payment.integration.event.notification.shipping_address_change_error.description' => 'No se pudo actualizar la dirección de envío en el pedido Mollie. Respuesta de la API Mollie {api_message}',

    'mollie.payment.integration.event.notification.order_line_changed_error.title'       => 'Error de sincronización de línea de pedido',
    'mollie.payment.integration.event.notification.order_line_changed_error.description' => 'No se pudo actualizar la línea de pedido para el pedido Mollie relacionado. Respuesta de la API Mollie {api_message}',

    'mollie.payment.integration.event.notification.order_ship_error.title'       => 'Error de sincronización de cambios en la tienda',
    'mollie.payment.integration.event.notification.order_ship_error.description' => 'No se pudo crear el envío para el pedido Mollie relacionado. Respuesta de la API Mollie {api_message}',

    'mollie.payment.integration.event.notification.order_total_changed.title'       => 'Evento de cambio en el total del pedido detectado',
    'mollie.payment.integration.event.notification.order_total_changed.description' => 'El cambio en el total del pedido no está soportado, por lo que este cambio no se sincroniza con Mollie',

    'mollie.payment.webhook.notification.order_line_refund_info.title'       => 'Línea de pedido Mollie modificada',
    'mollie.payment.webhook.notification.order_line_refund_info.description' => 'La línea de pedido ha sido reembolsada en el portal Mollie.',

    'mollie.payment.webhook.notification.invalid_shop_order.title'       => 'Cambio Mollie para pedido desconocido',
    'mollie.payment.webhook.notification.invalid_shop_order.description' => 'Se detectó un cambio desde Mollie pero no se encontró el pedido correspondiente en el sistema.',

    'mollie.payment.webhook.notification.invalid_credentials.title'       => 'Cambio Mollie no sincronizado',
    'mollie.payment.webhook.notification.invalid_credentials.description' => 'Ocurrió un error de autenticación. Token de acceso a la organización inválido.',

    'mollie.payment.webhook.notification.invalid_api_order.title'       => 'Cambio Mollie para pedido desconocido',
    'mollie.payment.webhook.notification.invalid_api_order.description' => 'Se detectó un cambio desde Mollie pero no se encontró el pago correspondiente en la API Mollie. Respuesta de la API Mollie {api_message}.',

    'mollie.payment.webhook.notification.network_communication_problem.title'       => 'Cambio Mollie no sincronizado',
    'mollie.payment.webhook.notification.network_communication_problem.description' => 'Se detectó un cambio desde Mollie pero no se pudo establecer conexión con la API Mollie. Detalles técnicos: {technical_message}.',

    'mollie.payment.webhook.notification.order_pay_error.title'       => 'Cambio Mollie no sincronizado',
    'mollie.payment.webhook.notification.order_pay_error.description' => 'Pedido pagado en el portal Mollie.',

    'mollie.payment.webhook.notification.order_expire_error.title'       => 'Cambio Mollie no sincronizado',
    'mollie.payment.webhook.notification.order_expire_error.description' => 'Pedido expirado en el portal Mollie.',

    'mollie.payment.webhook.notification.order_cancel_error.title'       => 'Cambio Mollie no sincronizado',
    'mollie.payment.webhook.notification.order_cancel_error.description' => 'Pedido cancelado en el portal Mollie.',

    'mollie.payment.webhook.notification.order_refund_error.title'       => 'Cambio Mollie no sincronizado',
    'mollie.payment.webhook.notification.order_refund_error.description' => 'Pedido reembolsado en el portal Mollie.',

    'mollie.payment.webhook.notification.order_line_cancel_info.title'       => 'Línea de pedido Mollie modificada',
    'mollie.payment.webhook.notification.order_line_cancel_info.description' => 'Línea de pedido cancelada en el portal Mollie.',

    'mollie_version_outdated_message' => 'Una nueva versión del módulo {versionNumber} está disponible. Por favor, descarga la última versión <a href="{downloadUrl}" target="_blank">aquí</a>',
    'mollie_system_offline_message'   => 'Tu sitio web está funcionando en modo offline. Dado que Mollie envía un mensaje a tu sitio cuando cambia el estado del pago, Mollie no podrá acceder a tu sitio mientras esté en modo offline.',

    'mollie_status_label'          => 'Estado Mollie',
    'mollie_gambio_status_label'   => 'Estado Gambio',
    'mollie_method_label'          => 'Método',
];
