<?php

$t_language_text_section_content_array = [
    'mollie_title'                   => 'Mollie',
    'mollie_description'             => 'Mollie betaalmodule',
    'mollie_version'                 => 'Versie',
    'mollie_test_mode'               => 'Testmodus',
    'mollie_live_token'              => 'Live API-key',
    'mollie_test_token'              => 'Test API-key',
    'mollie_live_token_msg'          => 'Je kunt je live API-Key vinden in je Mollie-profiel.',
    'mollie_test_token_msg'          => 'Je kunt je test-API Key vinden in je Mollie-profiel.',
    'mollie_verify'                  => 'Verifieer token',
    'mollie_support'                 => 'Support',
    'mollie_support_link'            => 'https://help.mollie.com/hc/nl',
    'mollie_status'                  => 'Status',
    'mollie_connect_success'         => 'Er is succesvol een verbinding tot stand gebracht met de Mollie-API. Sla de wijzigingen op om door te gaan met de betaalinstellingen.',
    'mollie_connect_failure'         => 'Er heeft zich een authenticatiefout voorgedaan. Ongeldig toegangstoken voor profiel.',
    'mollie_active'                  => 'Actief',
    'mollie_inactive'                => 'Inactief',
    'mollie_configure'               => 'Configureer',
    'mollie_payment_methods'         => 'Betaalmethodes',
    'mollie_configuration'           => 'Mollie-configuratie',
    'mollie_enabled'                 => 'Geactiveerd',
    'mollie_disabled'                => 'Gedeactiveerd',
    'mollie_connected'               => 'Verbonden',
    'mollie_not_connected'           => 'Niet verbonden',
    'mollie_notifications'           => 'Meldingen',
    'mollie_date'                    => 'Datum',
    'mollie_type'                    => 'Type',
    'mollie_order_number'            => 'Bestelnummer',
    'mollie_message'                 => 'Bericht',
    'mollie_details'                 => 'Details',
    'mollie_info'                    => 'Info',
    'mollie_warning'                 => 'Waarschuwing',
    'mollie_error'                   => 'Waarschuwing',
    'mollie_order_statuses'          => 'Status bestellingen',
    'mollie_created'                 => 'Status bestellingen',
    'mollie_authorized'              => 'Geautoriseerd',
    'mollie_paid'                    => 'Betaald',
    'mollie_refunded'                => 'Terugbetaald',
    'mollie_none'                    => 'Geen',
    'mollie_cancel'                  => 'Annuleren',
    'mollie_save_changes'            => 'Wijzigingen opslaan',
    'mollie_dashboard_title'         => 'Mollie Betaalinformatie',
    'mollie_payment_method'          => 'Betaalmethode',
    'mollie_checkout_type'           => 'Checkout type',
    'mollie_payment_status'          => 'Betaalstatus',
    'mollie_order_status'            => 'Status bestellingen',
    'mollie_paid_amount'             => 'Bedrag',
    'mollie_refunded_amount'         => 'Terugbetaald bedrag',
    'mollie_payment_link'            => 'Betaallink',
    'mollie_shipments'               => 'Verzendingen',
    'mollie_refunds'                 => 'Terugbetalingen',
    'mollie_open_in_mollie'          => 'Openen in Mollie',
    'mollie_payment_link_message'    => 'Het is niet mogelijk om de betaling handmatig te capturen. De betaling wordt automatisch gecaptured door Mollie.',
    'mollie_items'                   => 'Items',
    'mollie_amount'                  => 'Bedrag',
    'mollie_model'                   => 'Model',
    'mollie_products'                => 'Producten',
    'mollie_ordered_qty'             => 'Aantal besteld',
    'mollie_shipped_qty'             => 'Aantal verzonden',
    'mollie_shipped_at'              => 'Aantal verzonden',
    'mollie_qty_to_ship'             => 'Aantal te verzenden',
    'mollie_carrier'                 => 'Vervoerder',
    'mollie_tracking_code'           => 'Tracking-code',
    'mollie_tracking_url'            => 'Tracking-URL',
    'mollie_submit_shipment'         => 'Verzending verzenden',
    'mollie_copy_to_clipboard'       => 'Kopiëren naar klembord',
    'mollie_refund'                  => 'Terugbetaling',
    'mollie_refunded_qty'            => 'Aantal terugbetaald',
    'mollie_qty_to_refund'           => 'Aantal terug te betalen',
    'mollie_payment_refund'          => 'Terugbetaling',
    'mollie_refund_amount'           => 'Terugbetalingsbedrag',
    'mollie_refund_reason'           => 'Reden voor terugbetaling',
    'mollie_total'                   => 'Totaal',
    'mollie_price'                   => 'Prijs',
    'mollie_refund_message'          => 'Deze betaling is gedaan als onderdeel van een bestelling en het wordt aanbevolen om individuele orderregels terug te betalen.',
    'mollie_total_refunded'          => 'Bedrag al terugbetaald',
    'mollie_available_to_refund'     => 'Resterend bedrag voor terugbetaling',
    'mollie_refund_success'          => 'Betaling succesvol terugbetaald',
    'mollie_refund_error'            => 'Betaling kan niet worden terugbetaald. Reactie Mollie API: ',
    'mollie_not_refundable'          => 'Het totale bedrag is al terugbetaald',
    'mollie_not_shippable'           => 'Alle artikelen zijn al verzonden',
    'mollie_shipment_create_success' => 'Verzending succesvol aangemaakt op Mollie',
    'mollie_shipment_create_error'   => 'Kan geen verzending aanmaken voor gerelateerde Mollie-bestelling. Reactie Mollie API: {api_message}',
    'mollie_change_logo'             => 'Logo wijzigen',
    'mollie_change_logo_error'       => 'Logo uploaden mislukt',
    'mollie_orders_api'              => 'Orders API',
    'mollie_payments_api'            => 'Payments API',
    'mollie_unknown_error'           => 'Er is een onbekende fout opgetreden op de Mollie-API',
    'mollie_checkout_desc'           => 'Nadat je de bestelling hebt gecontroleerd, word je doorgestuurd naar de website van de betalingsprovider om je aankoop af te ronden.',

    'mollie_issuer_list_dropdown'    => 'Dropdown',
    'mollie_issuer_list_images'      => 'Lijst met afbeeldingen',

    'mollie_select_bank'             => 'Selecteer Bank',
    'mollie_card_holder'             => 'Kaarthouder',
    'mollie_card_number'             => 'Kaartnummer',
    'mollie_expiry_date'             => 'Vervaldatum',
    'mollie_verification_code'       => 'Verificatie code',

    'mollie_canceled_comment' => 'De klant heeft de betaling geannuleerd.',
    'mollie_expired_comment'  => 'De betaling is op Mollie verlopen.',
    'mollie_failed_comment'   => 'De betaling is mislukt en kan niet worden voltooid met de geselecteerde betalingsmethode.',

    'mollie.payment.integration.event.notification.order_cancel_error.title'       => 'Synchronisatie van winkelwijziging mislukt',
    'mollie.payment.integration.event.notification.order_cancel_error.description' => 'De bestelling van Mollie kan niet worden geannuleerd. Reactie Mollie API: {api_message}',

    'mollie.payment.integration.event.notification.billing_address_change_error.title'       => 'Synchronisatie van winkelwijziging mislukt',
    'mollie.payment.integration.event.notification.billing_address_change_error.description' => 'Het factuuradres van de Mollie-bestelling kan niet worden bijgewerkt. Reactie Mollie API: {api_message}',

    'mollie.payment.integration.event.notification.shipping_address_change_error.title'       => 'Synchronisatie van winkelwijziging mislukt',
    'mollie.payment.integration.event.notification.shipping_address_change_error.description' => 'Het factuuradres van de Mollie-bestelling kan niet worden bijgewerkt. Reactie Mollie API: {api_message}',

    'mollie.payment.integration.event.notification.order_line_changed_error.title'       => 'Order line synchronization failed',
    'mollie.payment.integration.event.notification.order_line_changed_error.description' => 'Bijwerken van orderregel voor gerelateerde Mollie-bestelling is mislukt. Reactie Mollie API: {api_message}',

    'mollie.payment.integration.event.notification.order_ship_error.title'       => 'Synchronisatie van winkelwijziging mislukt',
    'mollie.payment.integration.event.notification.order_ship_error.description' => 'Kan geen verzending aanmaken voor gerelateerde Mollie-bestelling. Reactie Mollie API: {api_message}',

    'mollie.payment.integration.event.notification.order_total_changed.title'       => 'Wijziging bestellingstotaal gedetecteerd',
    'mollie.payment.integration.event.notification.order_total_changed.description' => 'Wijziging van bestellingstotaal wordt niet ondersteund, dus deze wijziging wordt niet gesynchroniseerd met de Mollie',

    'mollie.payment.webhook.notification.order_line_refund_info.title'       => 'De orderregel van Mollie is gewijzigd',
    'mollie.payment.webhook.notification.order_line_refund_info.description' => 'Orderregel wordt terugbetaald in het Mollie-portaal.',

    'mollie.payment.webhook.notification.invalid_shop_order.title'       => 'Mollie-wijziging voor onbekende bestelling',
    'mollie.payment.webhook.notification.invalid_shop_order.description' => 'Wijziging van Mollie is gedetecteerd, maar de overeenkomende bestelling is niet gevonden in het systeem.',

    'mollie.payment.webhook.notification.invalid_credentials.title'       => 'De wijziging van Mollie is niet gesynchroniseerd',
    'mollie.payment.webhook.notification.invalid_credentials.description' => 'Er heeft zich een authenticatiefout voorgedaan. Ongeldig toegangstoken voor Organisatie.',

    'mollie.payment.webhook.notification.invalid_api_order.title'       => 'Mollie-wijziging voor onbekende bestelling',
    'mollie.payment.webhook.notification.invalid_api_order.description' => 'Er is een wijziging van Mollie gedetecteerd, maar de overeenkomende betaling is niet gevonden in de Mollie-API. Reactie Mollie API: {api_message}.',

    'mollie.payment.webhook.notification.network_communication_problem.title'       => 'De wijziging van Mollie is niet gesynchroniseerd',
    'mollie.payment.webhook.notification.network_communication_problem.description' => 'Verandering vanuit Mollie is gedetecteerd, maar netwerkverbinding met Mollie-API kon niet tot stand worden gebracht. Technische gegevens: {technical_message}.',

    'mollie.payment.webhook.notification.order_pay_error.title'       => 'De wijziging van Mollie is niet gesynchroniseerd',
    'mollie.payment.webhook.notification.order_pay_error.description' => 'Bestelling wordt betaald in het Mollie-portaal.',

    'mollie.payment.webhook.notification.order_expire_error.title'       => 'De wijziging van Mollie is niet gesynchroniseerd',
    'mollie.payment.webhook.notification.order_expire_error.description' => 'Bestelling is verlopen in het Mollie-portaal.',

    'mollie.payment.webhook.notification.order_cancel_error.title'       => 'De wijziging van Mollie is niet gesynchroniseerd',
    'mollie.payment.webhook.notification.order_cancel_error.description' => 'Bestelling is geannuleerd in het Mollie-portaal.',

    'mollie.payment.webhook.notification.order_refund_error.title'       => 'De wijziging van Mollie is niet gesynchroniseerd',
    'mollie.payment.webhook.notification.order_refund_error.description' => 'Bestelling wordt terugbetaald in het Mollie-portaal.',

    'mollie.payment.webhook.notification.order_line_cancel_info.title'       => 'De orderregel van Mollie is gewijzigd',
    'mollie.payment.webhook.notification.order_line_cancel_info.description' => 'Orderregel is geannuleerd in het Mollie-portaal.',
];